#!/bin/bash
git add -A
printf "\n"
echo Added!
printf "\n"
echo What should the commit message be?
read varname
printf "\n"
git commit -m "$varname"
printf "\n"
echo Commited!
printf "\n"
git push -u origin master
printf "\n"
echo Pushed!
echo Done!
