#!/bin/bash
git add -A
printf "\n"
echo Added!
printf "\n"
varname=$1
if [ $# -eq 0 ]
  then
    echo What should the commit message be?
    read varname
fi
printf "\n"
git commit -m "$varname"
printf "\n"
echo Commited!
printf "\n"
git push -u origin master
printf "\n"
echo Pushed!
echo Done!
